### ISSUE TITLE
ESP32 Optimized Compressor

### ISSUE THREAD

**Issue by BrianPugh** [BrianPugh/tamp#142]
Hey @BitsForPeople! 

I was giving [your esp32-optimized tamp implementation](https://github.com/BitsForPeople/esp-tamp) a try, as I would love to integrate those optimizations into this repo with the following goals:

1. Publishing a component package on the esp-component-registry.
2. Improve the performance of the micropython native module for `xtensawin` targets.

I made [a quick and dirty demo](https://github.com/BrianPugh/esp-tamp-demo) compressing the first 100,000 bytes of the enwik8 dataset. On an esp32, without the optimizations enabled, it compresses the data down to the expected 51,637 bytes in 5.76 seconds. With optimizations enabled, it seems to only compress 17 output bytes and then it thinks compression is done. Any ideas on why this may be? Thanks!

**Comment by BitsForPeople** [comment]
Thanks for testing and reporting. I'll try to reproduce using your demo and see what's wrong.

**Comment by BitsForPeople** [comment]
Seems there was an issue with the build system mixing the ESP32 and non-ESP32 header file variants. Should be fixed now (ccae6f189211b4a7148de0255a7ee2f9152f3299).

**Comment by BrianPugh** [comment]
It works now! thank you so much for the quick fix! On my esp32 it's 2.5x faster than the original implementation!

Are you ok with me merging in your code? I'll probably re-organize the files a little bit, but it'll keep your headers and I'll also add an acknowledgement section to the `README.md`

**Comment by BrianPugh** [comment]
Another question: are there speed-related reasons [for this function signature change here?](https://github.com/BitsForPeople/esp-tamp/blob/61db0120636352c772bf3ee1a1ab736a9e32563f/tamp/_c_src/tamp/compressor.h#L69). Or was it simplfy for convenience? I kept the return value as `void` incase I ever need to return an error code from that function (and so that its consistent with all the other tamp functions). In the code I merge in I'd like to not change the signature.

**Comment by BitsForPeople** [comment]
> Are you ok with me merging in your code?
Of course, please go ahead :)

**Comment by BitsForPeople** [comment]
> Another question: are there speed-related reasons [for this function signature change here?](https://github.com/BitsForPeople/esp-tamp/blob/61db0120636352c772bf3ee1a1ab736a9e32563f/tamp/_c_src/tamp/compressor.h#L69). Or was it simplfy for convenience?

I think it was more for convenience, not sure if it made any measurable performance improvement. Should be good to revert back to the original signature.

**Comment by BrianPugh** [comment]
This is now a part of v1.5.0!
