### ISSUE TITLE
Decompressor in C creates wrong output

### ISSUE THREAD

**Issue by DeeFuse** [BrianPugh/tamp#17]
Using the C code to compress and decompress a file does not result in the same uncompressed output.

The compressor produces the same output as the Python implementation but the C decomressor corrupts the data.
The first few bytes are correct but later into the decompression more and more bytes are wrong.

I used VisualStudio 2022 to build tamp as a x86 binary.

**Comment by DeeFuse** [comment]
I've teste it with 663 bytes of binary data, mostly 0x00 (60%) and also ran a test using 1024 byte "Lorem ipsum" text as plaintext.

I got some "converting const uint16_t to uint8_t" warnings, but adjusting the functions did not change the output.

**Comment by DeeFuse** [comment]
I used the code from the [c-profiler](https://github.com/BrianPugh/tamp/blob/096636ffc3556e0f87296b6641a6c653b2f316e9/tools/c-profiler/main.c#L81C1-L145C2) to test the functionality.

You can also have a look into the attached zip in my last comment.

**Comment by BrianPugh** [comment]
I just manually tested the pip-installed CLI on windows (I rarely use windows) with the enwik8 dataset, as well as a 10,000 long lorem ipsum, and everything is working on fine, so going to need more information to reproduce.

**Comment by BrianPugh** [comment]
you are correct, there must be a bug in the c-profiler code (honestly, that code was pretty rushed). I don't believe the bug is in the library itself, but in that script. I'll be investigating shortly and keep you updated. Issue is unrelated to Windows.

**Comment by BrianPugh** [comment]
Addressed in #18. I'll be releasing this and some minor performance improvements later today in v1.1.4. Thank you very much for the bug report!

**Comment by BrianPugh** [comment]
fixed in v1.1.4
